server:
  port: 8082

spring:
  thymeleaf:
    cache: false
  datasource:
    name: newbee-mall-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_newbee?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: rootroot
    hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 60000
        pool-name: hikariCP
        max-lifetime: 600000
        connection-timeout: 30000
        connection-test-query: SELECT 1

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 30000
    lettuce:
      pool:
        max-idle: 2 # 连接池中的最大空闲连接 默认8
        min-idle: 2 # 连接池中的最小空闲连接 默认0
        max-active: 2 # 连接池最大连接数 默认8 ，负数表示没有限制
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: Rlin99
    password: 123
    virtual-host: /Rlin


mybatis:
  mapper-locations: classpath:mapper/*.xml
